import { Injectable, Logger, OnModuleDestroy, OnModuleInit, ServiceUnavailableException } from "@nestjs/common";
import { ConfigService } from "@nestjs/config";
import { EventStatus, MarketStatus, OutcomeStatus } from "@prisma/client";
import { PrismaService } from "../../prisma/prisma.service";
type ProviderOutcome={name:string;price:number};type ProviderMarket={key:string;outcomes:ProviderOutcome[]};type ProviderBookmaker={key:string;markets:ProviderMarket[]};type ProviderEvent={id:string;sport_key:string;sport_title:string;commence_time:string;home_team:string;away_team:string;bookmakers:ProviderBookmaker[]};type FeedStatus={configured:boolean;running:boolean;lastStartedAt:string|null;lastCompletedAt:string|null;lastError:string|null;lastImported:number;requestsRemaining:number|null;requestsUsed:number|null};
@Injectable() export class OddsFeedService implements OnModuleInit,OnModuleDestroy{
 private readonly logger=new Logger(OddsFeedService.name);private timer?:NodeJS.Timeout;private syncing?:Promise<FeedStatus>;private state:FeedStatus={configured:false,running:false,lastStartedAt:null,lastCompletedAt:null,lastError:null,lastImported:0,requestsRemaining:null,requestsUsed:null};
 constructor(private readonly db:PrismaService,private readonly config:ConfigService){this.state.configured=Boolean(this.config.get<string>("ODDS_API_KEY"))}
 onModuleInit(){if(!this.state.configured)return;const minutes=Math.max(15,Number(this.config.get("ODDS_API_REFRESH_MINUTES")??60));this.timer=setInterval(()=>void this.sync().catch(error=>this.logger.error(error)),minutes*60_000);setTimeout(()=>void this.sync().catch(error=>this.logger.error(error)),5_000)}
 onModuleDestroy(){if(this.timer)clearInterval(this.timer)} status(){return{...this.state}} sync(){if(!this.state.configured)throw new ServiceUnavailableException("ODDS_API_KEY is not configured");if(!this.syncing)this.syncing=this.performSync().finally(()=>{this.syncing=undefined});return this.syncing}
 private async performSync(){this.state.running=true;this.state.lastStartedAt=new Date().toISOString();this.state.lastError=null;try{const response=await fetch(this.url(),{headers:{Accept:"application/json"},signal:AbortSignal.timeout(20_000)});this.readQuota(response.headers);if(!response.ok)throw new Error(`The Odds API returned ${response.status}: ${await response.text()}`);const events=await response.json() as ProviderEvent[];let imported=0;for(const event of events)if(await this.importEvent(event))imported++;this.state.lastImported=imported;this.state.lastCompletedAt=new Date().toISOString();return this.status()}catch(error){this.state.lastError=error instanceof Error?error.message:"Unknown odds feed error";throw new ServiceUnavailableException(this.state.lastError)}finally{this.state.running=false}}
 private url(){const sport=this.config.get<string>("ODDS_API_SPORT")??"upcoming";const params=new URLSearchParams({apiKey:this.config.getOrThrow<string>("ODDS_API_KEY"),regions:this.config.get<string>("ODDS_API_REGIONS")??"eu",markets:this.config.get<string>("ODDS_API_MARKETS")??"h2h",oddsFormat:"decimal",dateFormat:"iso"});return `https://api.the-odds-api.com/v4/sports/${encodeURIComponent(sport)}/odds?${params}`}
 private readQuota(headers:Headers){const remaining=headers.get("x-requests-remaining"),used=headers.get("x-requests-used");this.state.requestsRemaining=remaining==null?null:Number(remaining);this.state.requestsUsed=used==null?null:Number(used)} private bookmaker(event:ProviderEvent){const preferred=this.config.get<string>("ODDS_API_BOOKMAKER");return event.bookmakers.find(book=>book.key===preferred)??event.bookmakers[0]}
 private async importEvent(source:ProviderEvent){const bookmaker=this.bookmaker(source),providerMarket=bookmaker?.markets.find(market=>market.key==="h2h");if(!providerMarket?.outcomes.length)return false;const startsAt=new Date(source.commence_time);if(Number.isNaN(startsAt.getTime()))return false;const sportSlug=slug(source.sport_key.split("_")[0]||source.sport_title),competitionSlug=slug(source.sport_key),eventSlug=`odds-api-${source.id}`;const status=startsAt<=new Date()&&startsAt.getTime()>Date.now()-21600000?EventStatus.LIVE:EventStatus.SCHEDULED;const factor=Math.min(1,Math.max(.5,Number(this.config.get("ODDS_API_PRICE_FACTOR")??1)));
 await this.db.$transaction(async tx=>{const sport=await tx.sport.upsert({where:{slug:sportSlug},create:{slug:sportSlug,code:uniqueCode(source.sport_key),name:sportName(source.sport_key)},update:{active:true}});const competition=await tx.competition.upsert({where:{externalId:source.sport_key},create:{sportId:sport.id,externalId:source.sport_key,slug:competitionSlug,name:source.sport_title},update:{sportId:sport.id,name:source.sport_title,active:true}});const event=await tx.event.upsert({where:{externalId:source.id},create:{sportId:sport.id,competitionId:competition.id,externalId:source.id,slug:eventSlug,name:`${source.home_team} vs ${source.away_team}`,startsAt,status,homeTeamName:source.home_team,awayTeamName:source.away_team},update:{sportId:sport.id,competitionId:competition.id,name:`${source.home_team} vs ${source.away_team}`,startsAt,homeTeamName:source.home_team,awayTeamName:source.away_team}});await tx.event.updateMany({where:{id:event.id,status:{in:[EventStatus.SCHEDULED,EventStatus.LIVE]}},data:{status}});let market=await tx.market.findFirst({where:{eventId:event.id,key:"match-winner",line:null}});market=market?await tx.market.update({where:{id:market.id},data:{name:"Match winner",status:MarketStatus.OPEN,suspendedAt:null,suspensionReason:null}}):await tx.market.create({data:{eventId:event.id,key:"match-winner",name:"Match winner",status:MarketStatus.OPEN}});for(const [index,item] of providerMarket.outcomes.entries()){const key=outcomeKey(item.name,source),price=adjustedPrice(item.price,factor);const existing=await tx.outcome.findUnique({where:{marketId_key:{marketId:market.id,key}}});const outcome=await tx.outcome.upsert({where:{marketId_key:{marketId:market.id,key}},create:{marketId:market.id,key,name:item.name,status:OutcomeStatus.ACTIVE,currentOdds:price,sortOrder:index},update:{name:item.name,status:OutcomeStatus.ACTIVE,currentOdds:price,sortOrder:index}});if(Number(existing?.currentOdds??0)!==price)await tx.odds.create({data:{outcomeId:outcome.id,price,previousPrice:existing?.currentOdds,source:`the-odds-api:${bookmaker.key}`}})}});return true}
}
export function slug(value:string){return value.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")||"sports"} export function uniqueCode(value:string){return `ODDS_${value.toUpperCase().replace(/[^A-Z0-9]+/g,"_")}`.slice(0,48)} export function sportName(key:string){return({soccer:"Football",basketball:"Basketball",tennis:"Tennis",baseball:"Baseball",icehockey:"Ice Hockey",americanfootball:"American Football"} as Record<string,string>)[key.split("_")[0]]??"Sports"} export function adjustedPrice(price:number,factor:number){return Math.max(1.01,Math.floor(price*factor*100)/100)} export function outcomeKey(name:string,event:Pick<ProviderEvent,"home_team"|"away_team">){if(name===event.home_team)return"home";if(name===event.away_team)return"away";if(name.toLowerCase()==="draw")return"draw";return slug(name)}
